version: "3.4"

volumes:
  react_node_modules:

services:
  react-client:
    build: react-client
    image: react-client
    restart: "no"
    volumes:
      - ./react-client/:/app
      - react_node_modules:/app/node_modules
    ports:
      - 3000:3000
    env_file:
      - project.env

  react-opt-client:
    build: react-opt-client
    image: react-opt-client
    restart: "no"
    volumes:
      - ./react-opt-client/:/app
      - react_node_modules:/app/node_modules
    ports:
      - 3001:3001
    env_file:
      - project.env

  preact-client:
    build: preact-client
    image: preact-client
    restart: "no"
    volumes:
      - ./preact-client/:/app
      - react_node_modules:/app/node_modules
    ports:
      - 3002:3002
    env_file:
      - project.env

  preact-opt-client:
    build: preact-opt-client
    image: preact-opt-client
    restart: "no"
    volumes:
      - ./preact-opt-client/:/app
      - react_node_modules:/app/node_modules
    ports:
      - 3003:3003
    env_file:
      - project.env

  next-react:
    build: next-react
    image: next-react
    restart: "no"
    ports:
      - 3004:3004
    env_file:
      - project.env

  astro-react:
    build: astro-react
    image: astro-react
    restart: "no"
    ports:
      - 3005:8080
    env_file:
      - project.env

  next-preact:
    build: next-preact
    image: next-preact
    restart: "no"
    ports:
      - 3006:3006
    env_file:
      - project.env

  astro-preact:
    build: astro-preact
    image: astro-preact
    restart: "no"
    ports:
      - 3007:8080
    env_file:
      - project.env

  qwik:
    build: qwik
    image: qwik
    restart: "no"
    ports:
      - 3008:3000
    env_file:
      - qwik/.env.production

  solid:
    build: solid
    image: solid
    restart: "no"
    ports:
      - 3009:3000
    env_file:
      - solid/.env.production