version: "3.4"

volumes:
  react_node_modules:

services:
  react-client:
    build: react-client
    image: react-client
    restart: "no"
    volumes:
      - ./react-client/:/app
      - react_node_modules:/app/node_modules
    ports:
      - 3000:3000
    env_file:
      - project.env

  react-opt-client:
    build: react-opt-client
    image: react-opt-client
    restart: "no"
    volumes:
      - ./react-opt-client/:/app
      - react_node_modules:/app/node_modules
    ports:
      - 3001:3001
    env_file:
      - project.env

  preact-client:
    build: preact-client
    image: preact-client
    restart: "no"
    volumes:
      - ./preact-client/:/app
      - react_node_modules:/app/node_modules
    ports:
      - 3002:3002
    env_file:
      - project.env

  preact-opt-client:
    build: preact-opt-client
    image: preact-opt-client
    restart: "no"
    volumes:
      - ./preact-opt-client/:/app
      - react_node_modules:/app/node_modules
    ports:
      - 3003:3003
    env_file:
      - project.env

  next-app:
    build: next-app
    image: next-app
    restart: "no"
    ports:
      - 3004:3004
    env_file:
      - project.env

  astro:
    build: astro
    image: astro
    restart: "no"
    ports:
      - 3005:8080
    env_file:
      - project.env